apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pm-340-spike-coordinator.serviceAccountName" . }}
rules:
- apiGroups: ["batch"]
  resources: ["pods", "jobs"]
  verbs: ["get", "list", "describe", "create"]
