---
environments:
  default:
    values:
      - github:
          accesstoken: ref+awssecrets://github?region=us-west-2#/access-token
      - testnet:
          name: o1labs-berkeley-upgrade
          platform: sandbox
          image: gcr.io/o1labs-192920/mina-daemon:2.0.0berkeley-rc1-testing-generate-fork-config-for-hf-test-57701d1-bullseye-devnet-hardfork
      - keys:
          libp2pPassword: ref+awssecrets://partners/qanet/node-1?region=us-west-2#/libp2p-password
          discoveryLibp2p: ref+awssecrets://partners/qanet/node-1?region=us-west-2#/libp2p
          discoveryLibp2pPeerid: ref+awssecrets://partners/qanet/node-1?region=us-west-2#/libp2p.peerid
          walletPassword: ref+awssecrets://partners/qanet/node-1?region=us-west-2#/key-password
          walletKey: ref+awssecrets://partners/qanet/node-1?region=us-west-2#/key
          walletPub: ref+awssecrets://partners/qanet/node-1?region=us-west-2#/key.pub
      - seeds:
          seed0Libp2pPeerid: ref+awssecrets://partners/qanet/seed-0?region=us-west-2#/libp2p.peerid
          seed1Libp2pPeerid: ref+awssecrets://partners/qanet/seed-1?region=us-west-2#/libp2p.peerid
---
releases:
- name: "node-1"
  namespace: "{{ .Values.testnet.name }}"
  chart: git::https://git:{{ .Values.github.accesstoken | fetchSecretValue }}@github.com/MinaFoundation/helm-charts.git@mina-daemon?ref=main
  values:
    - deployment:
        testnet: o1labs-berkeley-upgrade
        name: "{{ .Values.testnet.name }}-mina-node-1"
        image: {{ .Values.testnet.image }}
        customEntrypoint:
          enabled: true
          entrypoint: mina
        peerListURL: https://storage.googleapis.com/o1labs-gitops-infrastructure/o1labs-berkeley-upgrade/seed_list_o1labs_berkeley_upgrade.txt
        genesisLedgerURL: http://673156464838-mina-genesis-ledgers.s3-website-us-west-2.amazonaws.com/o1labs-berkeley-upgrade/genesis_ledger.json
    - podAnnotations:
        karpenter.sh/do-not-evict: "true"
    - node:
        name: node-1
        role: node
        seedFlags: false
        exposeGraphql: true
        logLevel: Debug
        filelogLevel: Debug
        metrics:
          enabled: true
        libp2pKeys:
          enabled: true
          legacy: false
        walletKeys:
          enabled: true
        enableFlooding: true
        secrets:
          libp2pPassword: {{ .Values.keys.libp2pPassword | fetchSecretValue | quote }}
          discoveryLibp2p: {{ .Values.keys.discoveryLibp2p | fetchSecretValue | quote }}
          discoveryLibp2pPeerid: {{ .Values.keys.discoveryLibp2pPeerid | fetchSecretValue }}
          walletPassword: {{ .Values.keys.walletPassword | fetchSecretValue | quote }}
          walletKey: {{ .Values.keys.walletKey | fetchSecretValue | quote }}
          walletPub: {{ .Values.keys.walletPub | fetchSecretValue}}
        archive:
          enabled: true
          address: "archive.{{ .Values.testnet.name }}.svc.cluster.local:3086"
        extraEnvVars:
          - name: RAYON_NUM_THREADS
            value: "6"
    - resources:
        memoryRequest: 16Gi
        cpuRequest: 4
        memoryLimit: 20Gi
        cpuLimit: 6
    - healthcheck:
        enabled: true
