---
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

environments:
  default:
    values:
      - database:
          host: sandbox-spike-mina-archive-postgresql
          username: mina
          password: ref+awssecrets://punkpoll/archive?region=us-west-2#/password
      - testnet:
          name: spike
          platform: sandbox
          image: gcr.io/o1labs-192920/mina-archive:2.0.0rampup5-55b7818-focal
          archiveName: mina-archive
      - github:
          accesstoken: ref+awssecrets://github?region=us-west-2#/access-token
---
releases:
- name: "{{ .Values.testnet.platform }}-{{ .Values.testnet.name }}-{{ .Values.testnet.archiveName }}"
  namespace: "pm-344-public-postgres"
  chart: git::https://git:{{ .Values.github.accesstoken | fetchSecretValue }}@github.com/MinaFoundation/helm-charts.git@mina-archive?ref=main
  version: 2.0.0
  values:
    - archive:
        global:
          storageClass: ebs-gp3-encrypted
        testnet: {{ .Values.testnet.name }}
        metrics:
          enabled: true
        initFromDump: false
        postgresHost: {{ .Values.database.host }}
        remoteSchemaAuxFiles:
          - https://raw.githubusercontent.com/MinaProtocol/mina/55b78189c46e1811b8bdb78864cfa95409aeb96a/src/app/archive/create_schema.sql
          - https://raw.githubusercontent.com/MinaProtocol/mina/55b78189c46e1811b8bdb78864cfa95409aeb96a/src/app/archive/zkapp_tables.sql
        image: {{ .Values.testnet.image }}
        enablePostgresDB: true
    - podAnnotations:
        karpenter.sh/do-not-evict: "true"
    - postgresql:
        auth:
          username: {{ .Values.database.username }}
          password: {{ .Values.database.password | fetchSecretValue }}
        audit:
          logHostname: true
          logConnections: true
          logDisconnections: true
          clientMinMessages: debug
        primary:
          service:
            externalTrafficPolicy: Local
            type: LoadBalancer
            annotations:
              external-dns.alpha.kubernetes.io/hostname: PM-344.minaprotocol.network
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
              service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
              service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
              service.beta.kubernetes.io/aws-load-balancer-type: nlb
              # Annotations for access logs - will be soon deprecated in favor of "aws-load-balancer-attributes"
              service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
              service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "david-access-logs-nlb-debug"
              service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "psql-app"
              # LB attributes - you can concatenate values separated with comma signs ','
              service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=false"
    - resource:
        memoryRequest: 4Gi
        cpuRequest: 2
        memoryLimit: 4Gi
        cpuLimit: 2
