---
environments:
  default:
    values:
      - github:
          accesstoken: ref+awssecrets://github?region=us-west-2#/access-token
      - testnet:
          name: mainnet
          platform: sandbox
          image: minaprotocol/mina-daemon:1.4.0-c980ba8-bullseye-mainnet
---
releases:
- name: "{{ .Values.testnet.platform }}-{{ .Values.testnet.name }}-mina-snark-worker-seq"
  namespace: "{{ .Values.testnet.name }}"
  chart: git::https://git:{{ .Values.github.accesstoken | fetchSecretValue }}@github.com/MinaFoundation/helm-charts.git@mina-daemon?ref=main
  values:
    - deployment:
        testnet: mainnet
        name: "{{ .Values.testnet.name }}-mina-snark-worker-seq"
        image: {{ .Values.testnet.image }}
        customEntrypoint:
          enabled: true
          entrypoint: mina
    - podAnnotations:
        karpenter.sh/do-not-evict: "true"
    - node:
        name: snark-worker
        role: snark-worker
        daemonMode:
          snarkWorker: true
        replicas: 9
        logLevel: Debug
        metrics:
          enabled: true
        libp2pKeys:
          enabled: false
          legacy: true
        walletKeys:
          enabled: false
        daemonAddress: sandbox-mainnet-mina-snark-coordinator-0:8301
        proofLevel: full
        extraEnvVars:
          - name: RAYON_NUM_THREADS
            value: "8"
    - resources:
        memoryRequest: 6Gi
        cpuRequest: 10
        memoryLimit: 6Gi
        cpuLimit: 10
    - healthcheck:
        enabled: false
