---
environments:
  default:
    values:
      - github:
          accesstoken: ref+awssecrets://github?region=us-west-2#/access-token
      - testnet:
          name: mainnet
          platform: sandbox
          image: minaprotocol/mina-daemon:1.4.0-c980ba8-bullseye-mainnet
          genesisLedgerURL: http://673156464838-mina-genesis-ledgers.s3-website-us-west-2.amazonaws.com/mainnet/genesis_ledger.json
          peerListURL: https://storage.googleapis.com/seed-lists/mainnet_seeds.txt
      - keys:
          discoveryLibp2p: ref+awssecrets://staging/mainnet/bp-0?region=us-west-2#/libp2p
          discoveryLibp2pPeerid: ref+awssecrets://staging/mainnet/bp-0?region=us-west-2#/libp2p.peerid
          libp2pPassword: ref+awssecrets://staging/mainnet/bp-0?region=us-west-2#/libp2p-password
          walletKey: ref+awssecrets://staging/mainnet/bp-0?region=us-west-2#/key
          walletPassword: ref+awssecrets://staging/mainnet/bp-0?region=us-west-2#/key-password
          walletPub: ref+awssecrets://staging/mainnet/bp-0?region=us-west-2#/key.pub

---
releases:
- name: "{{ .Values.testnet.platform }}-{{ .Values.testnet.name }}-mina-block-producer-0"
  namespace: "{{ .Values.testnet.name }}"
  chart: git::https://git:{{ .Values.github.accesstoken | fetchSecretValue }}@github.com/MinaFoundation/helm-charts.git@mina-daemon?ref=main
  values:
    - deployment:
        testnet: {{ .Values.testnet.name }}
        name: "{{ $.Values.testnet.name }}-mina-block-producer-0"
        image: {{ .Values.testnet.image }}
        runtimeConfig:
        customEntrypoint:
          enabled: true
          entrypoint: mina
        peerListURL: {{ .Values.testnet.peerListURL }}
        genesisLedgerURL: {{ .Values.testnet.genesisLedgerURL }}
        uptime:
          enabled: true
          url: "https://uptime-payload-inspector.minaprotocol.tools/submit/stats"
    - podAnnotations:
        karpenter.sh/do-not-evict: "true"
    - node:
        name: block-producer-0
        role: block-producer
        daemonMode:
          blockProducer: true
        seedFlags: false
        exposeGraphql: true
        logLevel: Info
        fileLogLevel: Info
        logSnarkWorkGossip: true
        generateGenesisProof: true
        logPrecomputedBlocks: true
        metrics:
          enabled: true
        libp2pKeys:
          enabled: true
          legacy: true
        walletKeys:
          enabled: true
        secrets:
          libp2pPassword: {{ .Values.keys.libp2pPassword | fetchSecretValue | quote }}
          discoveryLibp2p: {{ .Values.keys.discoveryLibp2p | fetchSecretValue | quote }}
          discoveryLibp2pPeerid: {{ .Values.keys.discoveryLibp2pPeerid | fetchSecretValue }}
          walletPassword: {{ .Values.keys.walletPassword | fetchSecretValue | quote }}
          walletKey: {{ .Values.keys.walletKey | fetchSecretValue | quote }}
          walletPub: {{ .Values.keys.walletPub | fetchSecretValue}}
        archive:
          enabled: true
          address: "{{ .Values.testnet.platform }}-{{ .Values.testnet.name }}-mina-archive:3086"
        extraEnvVars:
          - name: RAYON_NUM_THREADS
            value: "6"
    - resources:
        memoryRequest: 16Gi
        cpuRequest: 8
        ephemeralStorageRequest: 10Gi
        memoryLimit: 16Gi
        cpuLimit: 8
        ephemeralStorageLimit: 10Gi
    - healthcheck:
        enabled: true
