---
environments:
  default:
    values:
      - github:
          accesstoken: ref+awssecrets://github?region=us-west-2#/access-token
      - network:
          name: qanet
          platform: partners
          image: gcr.io/o1labs-192920/mina-daemon:2.0.0berkeley-rc1-1551e2f-focal-berkeley
          genesisLedgerURL: http://673156464838-mina-genesis-ledgers.s3-website-us-west-2.amazonaws.com/qanet/genesis_ledger.json
      - keys:
          libp2pPassword: ref+awssecrets://staging/berkeley/block-producer-0?region=us-west-2#/libp2p-password
          discoveryLibp2p: ref+awssecrets://staging/berkeley/block-producer-0?region=us-west-2#/libp2p
          discoveryLibp2pPeerid: ref+awssecrets://staging/berkeley/block-producer-0?region=us-west-2#/libp2p.peerid
          walletPassword: ref+awssecrets://staging/berkeley/block-producer-0?region=us-west-2#/key-password
          walletKey: ref+awssecrets://staging/berkeley/block-producer-0?region=us-west-2#/key
          walletPub: ref+awssecrets://staging/berkeley/block-producer-0?region=us-west-2#/key.pub
      - seeds:
          seed0Libp2pPeerid: ref+awssecrets://partners/qanet/seed-0?region=us-west-2#/libp2p.peerid
          seed1Libp2pPeerid: ref+awssecrets://partners/qanet/seed-1?region=us-west-2#/libp2p.peerid
---
releases:
- name: "node-0"
  namespace: "{{ .Values.network.name }}"
  chart: git::https://git:{{ .Values.github.accesstoken | fetchSecretValue }}@github.com/MinaFoundation/helm-charts.git@mina-daemon?ref=main
  values:
    - deployment:
        testnet: {{ .Values.network.name }}
        name: "{{ .Values.network.name }}-mina-node-0"
        image: {{ .Values.network.image }}
        customEntrypoint:
          enabled: true
          entrypoint: mina
        peerListURL: https://673156464838-mina-seed-lists.s3.us-west-2.amazonaws.com/partners/qanet-seed-nodes.txt
        genesisLedgerURL: {{ .Values.network.genesisLedgerURL }}
    - podAnnotations:
        karpenter.sh/do-not-evict: "true"
    - node:
        name: node-0
        role: node
        seedFlags: false
        exposeGraphql: true
        logLevel: Warn
        filelogLevel: Warn
        metrics:
          enabled: true
        libp2pKeys:
          enabled: true
        walletKeys:
          enabled: true
        enableFlooding: true
        archive:
          enabled: true
          address: "archive:3086"
        secrets:
          libp2pPassword: {{ .Values.keys.libp2pPassword | fetchSecretValue | quote }}
          discoveryLibp2p: {{ .Values.keys.discoveryLibp2p | fetchSecretValue | quote }}
          discoveryLibp2pPeerid: {{ .Values.keys.discoveryLibp2pPeerid | fetchSecretValue }}
          walletPassword: {{ .Values.keys.walletPassword | fetchSecretValue | quote }}
          walletKey: {{ .Values.keys.walletKey | fetchSecretValue | quote }}
          walletPub: {{ .Values.keys.walletPub | fetchSecretValue}}
        txnGenerator:
          enabled: true
        extraEnvVars:
          - name: RAYON_NUM_THREADS
            value: "6"
    - resources:
        memoryRequest: 16Gi
        cpuRequest: 4
        memoryLimit: 20Gi
        cpuLimit: 6
    - healthcheck:
        enabled: true
