name: 'Test Github Actions'

on:
  push:
    branches: [main]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-runner-default:
    runs-on: minafoundation-default-runners
    name: Test minafoundation-default-runners
    steps:
    - uses: actions/checkout@v3
    - name: Test Default Runner
      id: test
      run: |
        echo "test"
  test-runner-large:
    runs-on: minafoundation-default-runners
    name: Test minafoundation-large-runners
    steps:
    - uses: actions/checkout@v3
    - name: Test Large Runner
      id: test
      run: |
        echo "test"
  test-runner-xlarge:
    runs-on: minafoundation-default-runners
    name: Test minafoundation-xlarge-runners
    steps:
    - uses: actions/checkout@v3
    - name: Test xLarge Runner
      id: test
      run: |
        echo "test"
  test-runner-2xlarge:
    runs-on: minafoundation-default-runners
    name: Test minafoundation-2xlarge-runners
    steps:
    - uses: actions/checkout@v3
    - name: Test 2xLarge Runner
      id: test
      run: |
        echo "test"
