name: 'Test Github Actions'

on:
  push:
    branches: [main]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-on-main:
    runs-on: minafoundation-default-runners
    name: Test Run (Main) - ${{ github.ref }}
    steps:
    - uses: actions/checkout@v3
    - name: Echo Test
      id: test
      run: |
        echo "test - ${{ github.ref }}"
