name: 'Test Github Actions'

on:
  push:
    branches: [main]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test-runner-default:
    runs-on: minafoundation-default-runners
    name: Test minafoundation-default-runners
    steps:
    - uses: actions/checkout@v3
    - name: Test Default Runner
      id: test
      run: |
        echo "test"
        docker build -t test .
  test-runner-default2:
    runs-on: minafoundation-default-runners
    name: Test minafoundation-default-runners2
    steps:
    - uses: actions/checkout@v3
    - name: Test Default Runner
      id: test2
      run: |
        echo "test"
        docker build -t test .
  test-runner-default3:
    runs-on: minafoundation-default-runners
    name: Test minafoundation-default-runners3
    steps:
    - uses: actions/checkout@v3
    - name: Test Default Runner
      id: test3
      run: |
        echo "test"
        docker build -t test .
